### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap-ui#86] opened 2017-09-26 20:56 UTC
Think the error message to the right should be `isn't` supported.  Also it shouldn't be 2 messages, and am not sure if we need to display both of those error alerts.

![data mapper error msg](https://user-images.githubusercontent.com/351660/30883794-5c323db8-a2db-11e7-95ef-e52411876972.png)

@dongniwang FYI

**Comment by igarashitm** [comment] 2017-09-26 21:00
Actually this is an INFO message to be used in the validation result, wondering why it's showing as an ERROR

**Comment by igarashitm** [comment] 2017-09-26 21:05
And the duplicate validation error is caused by atlasmap/atlasmap#127 I'm working on as a part of atlasmap/atlasmap#188

**Comment by gashcrumb** [comment] 2017-09-27 12:50
@igarashitm ah, k, so this probably duplicates that issue then?

**Comment by igarashitm** [comment] 2017-09-27 15:26
I think we'll need to fix that "is supported" thing  at UI side after refactoring validation at runtime side, that INFO message shouldn't be displayed as an ERROR. Let's see after it's merged.

**Closed as completed** 2017-10-19 14:37 UTC
Labels: bug

**Comment by igarashitm** [comment] 2017-10-19 14:40
We still have a major bug #112 though, it should get a bit better, at least INFO message is no longer shown as an error.
