### ISSUE TITLE
[datamapper]Endless spinning cursor when no "data shape properties" available

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap-ui#60] opened 2017-07-27 12:33 UTC
on https://syndesis-staging.b6ff.rh-idev.openshiftapps.com with Chrome Version 59.0.3071.115 (Build officiel) (64 bits) on Windows 10
I created an "integration" with  2 http connectors (one Get and one POST) with dummy value
I then tried to add a "datamapping"

I have an endless spinning cursor:
![image](https://user-images.githubusercontent.com/1105127/28670333-7d0fe82e-72d8-11e7-9117-c084a6dd51d2.png)

in Chrome console I have this error which sees related to my issue:
> vendor.4093d0c….bundle.js:148 ERROR TypeError: Cannot read property 'initCfg' of undefined
>     at t.targetSupportsTemplate (vendor.4093d0c….bundle.js:750)
>     at Object.p.ɵvid.e [as updateDirectives] (main.48c2ac0….bundle.js:1)
>     at Object.updateDirectives (vendor.4093d0c….bundle.js:260)
>     at Gn (vendor.4093d0c….bundle.js:260)
>     at rr (vendor.4093d0c….bundle.js:260)
>     at er (vendor.4093d0c….bundle.js:260)
>     at Gn (vendor.4093d0c….bundle.js:260)
>     at rr (vendor.4093d0c….bundle.js:260)
>     at er (vendor.4093d0c….bundle.js:260)
>     at Gn (vendor.4093d0c….bundle.js:260)
>     at rr (vendor.4093d0c….bundle.js:260)
>     at nr (vendor.4093d0c….bundle.js:260)
>     at Object.Gn [as checkAndUpdateView] (vendor.4093d0c….bundle.js:260)
>     at t.detectChanges (vendor.4093d0c….bundle.js:337)
>     at l.initializeMapper (2.46b854e….chunk.js:1)

**Comment by apupier** [comment] 2017-07-27 12:37
same issue on Firefox

> ERROR TypeError: t is undefined
> Stack trace:
> onrB/o</t.prototype.targetSupportsTemplate@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:750:176376
> c/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.48c2ac0d922f133ada40.bundle.js:1:202227
> updateDirectives@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:8539
> Gn@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:4424
> rr@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:7264
> er@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:6662
> Gn@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:4559
> rr@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:7264
> er@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:6662
> Gn@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:4559
> rr@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:7264
> nr@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:6927
> Gn@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:260:4449
> 3j3K/</_a</t.prototype.detectChanges@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:337:24066
> 1dQ6/C</l.prototype.initializeMapper@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/2.46b854e5c6a6999174be.chunk.js:1:9079
> onSave/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/2.46b854e5c6a6999174be.chunk.js:1:8788
> ZSR1/</</E</F</t.prototype.invokeTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:10887
> onInvokeTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/vendor.4093d0c4ca5d3d801a23.bundle.js:316:8008
> ZSR1/</</E</F</t.prototype.invokeTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:10800
> ZSR1/</</E</E</n.prototype.runTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:6056
> t/this.invoke@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:11848
> e@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:15:52

**Comment by gashcrumb** [comment] 2017-07-27 12:56
The problem I think is really that HTTP POST and GET actions don't have any data shape properties, at least as far as I'm aware.  So I think we probably need to make the datamapper step available in the list on the condition that the integration has connections that can map data.

Unless I suppose you could just map properties/headers?

**Comment by apupier** [comment] 2017-07-27 13:02
ok, would be nice to provide an error message explaining it to the user

**Comment by apupier** [comment] 2017-07-27 13:17
ans also to not propose to add a Datamapper if it is not supported (still wasn't able to access it with twitter and salesforce aad/or timer connectors) Seems that there are different errors in console log but still no datamapper :(

**Comment by gashcrumb** [comment] 2017-07-27 13:24
Yeah, so there's a few things to watch out for.  Some of the deployed integrations and actions on staging aren't fully fleshed out, so they're either missing input or output types when they should really have them.

I think at the moment the data mapper host is still kinda hard-coded for the summit demo, let me go and fix that up a bit today, namely this one -> https://github.com/syndesisio/syndesis-ui/issues/604

**Comment by jbakermd** [comment] 2017-07-27 16:41
Assigning this to you @gashcrumb bc it sounds like you're handling this. Feel free to assign to me if needed.

**Comment by gashcrumb** [comment] 2017-07-27 16:51
@jbakermd sounds good!

**Comment by gashcrumb** [comment] 2017-08-02 14:27
Turns out this is a duplicate of https://github.com/syndesisio/syndesis-ui/issues/562

**Closed as completed** 2017-08-02 14:27 UTC
Labels: bug
