### ISSUE TITLE
Duplicate objects for input and output

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap-ui#41] opened 2017-07-21 07:07 UTC
When creating a Twitter to Salesforce integration (with the latest atlasmap fixes applied), the UI seems to add duplicated objects randomly (see screenshot):

![image](https://user-images.githubusercontent.com/99080/28452612-bf0421a8-6df3-11e7-816d-cf92cfbe7d07.png)

Also, tons on error message occur in the console:

![image](https://user-images.githubusercontent.com/99080/28452662-05be238c-6df4-11e7-929f-041283503f92.png)

**Comment by rhuss** [comment] 2017-07-21 07:10
Maybe this error is also related:

![image](https://user-images.githubusercontent.com/99080/28452745-69756c3c-6df4-11e7-926a-40c60c4c6973.png)

**Comment by jbakermd** [comment] 2017-07-21 13:49
The validation errors shown in the second screen shot is not related. We have a validation service that's currently in progress. That validation service is return two errors (when it should show one) for that error right now.

**Comment by jbakermd** [comment] 2017-07-21 13:51
@gashcrumb fyi. Looks like the Syndesis UI is creating dupe sources and targets in new integrations.

**Comment by gashcrumb** [comment] 2017-07-27 15:44
@jbakermd have a PR open where I've verified (just via some console logging) that the host component is only passing one instance of a source/target -> https://github.com/syndesisio/syndesis-ui/pull/686

I think the problem could be that the syndesis-ui treats the data mapper component as disposable, i.e. you navigate away from the page and the UI gets destroyed, however I think the underlying data mapper services are still effectively in-memory.  So when you go back into the data mapper the previous state is there, and new state is added as well.

It might just be a matter of dealing with re-initialization of the data mapper's angular services when the user goes back into the data mapper view.  Or maybe a 'destroy()' method I can call from the host component's `ngOnDestroy()`

Also take a look at this newly created duplicate issue -> https://github.com/syndesisio/syndesis-ui/issues/680 I linked, has good steps to reproduce.

**Comment by jbakermd** [comment] 2017-07-27 16:37
Ah that explains it completely. I was under the impression the data mapper was created and destroyed every time the user clicked that part of the integration screen. Given the interesting hoops I had to jump through to dynamically include/destroy components within the modal component, I would highly recommend not trying to mess with dynamically recreating the data mapper component, but instead add a way to reset the config to zero before initialization happening again. 

Something like a configModel.reset() method. That method would need to: 

- discard configured documents (sourcedocs/targetdocs/propertydoc/constantdoc)
- discard configured mapping information (the mappingdefinition model)
- re-run any initialization that happened in the config model constructor (i think property/constant docs are initialized there).

**Comment by jbakermd** [comment] 2017-07-27 16:37
@gashcrumb thanks a lot for narrowing this down.

**Comment by gashcrumb** [comment] 2017-07-27 16:47
@jbakermd np!  Yeah, a `configModel.reset()` function would be perfect, then I can call that before re-initializing.  And yeah, to clarify all the UI components do get destroyed, but thanks to angular all the services that the UI uses to do it's thing are singletons, and they hang around.

We probably would have spotted this sooner if we had some more example integrations with different types, as going from one integration to a different one with different types would have exposed this issue right away.  But, it is what it is :-)  Thanks!

**Comment by jbakermd** [comment] 2017-07-27 16:54
Ah, that's it. Its that the services are hanging around. This is a new bug since summit then because I changed the config model's parent to the initializationservice. Before this change, a host component would create a totally new config model, set it on all of the services and we'd be golden. After the change, there's just one config sitting around and its magically set on all of the services by the initservice's constructor for simplicity. The reset() method is definitely needed on config model now.

**Comment by jbakermd** [comment] 2017-07-28 18:51
Ok, there are going to be two PRs here, one for the data mapper side, and one for the syndesis side.

Data mapper side is merged, that's PR: https://github.com/atlasmap/atlasmap-ui/pull/65

Syndesis side PR: https://github.com/syndesisio/syndesis-ui/pull/699

**Comment by jbakermd** [comment] 2017-07-28 19:10
@gashcrumb please review https://github.com/syndesisio/syndesis-ui/pull/699 (or have someone else review it).

**Comment by jbakermd** [comment] 2017-07-28 19:26
This is fixed.

**Closed as completed** 2017-07-28 19:26 UTC
Labels: bug
